from typing import Any


SCENARIO_MARKERS: dict[str, int] = {
    "entrusted": 3,
    "embezzled": 3,
    "misappropriated": 3,
    "accountant": 2,
    "employee": 2,
    "clerk": 2,
    "servant": 2,
    "agent": 2,
    "murder": 3,
    "killed": 3,
    "caused death": 3,
    "riot": 2,
    "mob": 2,
    "stampede": 2,
    "death": 2,
    "injury": 2,
    "fraud": 2,
    "forged": 2,
    "kidnapped": 3,
    "used for personal": 3,
    "personal expenses": 3,
    "company funds": 3,
    "which provision applies": 2,
    "which provisions apply": 2,
    "which sections apply": 2,
    "under the law": 1,
    "charged": 2,
    "accused": 2,
    "defendant": 2,
    "found": 2,
    "lost wallet": 3,
    "found on the road": 3,
    "later decided to keep": 3,
    "kept it for personal use": 3,
}


LEGAL_CONCEPTS: dict[str, dict[str, Any]] = {
    "murder": {
        "markers": (
            "murder",
            "qatl-e-amd",
            "intentional killing",
            "killed a person",
            "commit a murder",
            "committed murder",
        ),
        "queries": (
            "Section 300 definition of qatl-e-amd",
            "Section 302 punishment of qatl-e-amd",
        ),
        "preferred_sections": {"300", "302"},
        "keywords": {
            "murder",
            "qatl",
            "death",
            "intention",
            "knowledge",
            "punishment",
        },
    },
    "theft": {
        "markers": (
            "theft",
            "stole",
            "stolen",
            "stealing",
        ),
        "queries": (
            "Section 378 definition of theft",
            "Section 379 punishment for theft",
        ),
        "preferred_sections": {"378", "379"},
        "keywords": {
            "theft",
            "dishonestly",
            "movable",
            "property",
            "punishment",
        },
    },
    "breach_of_trust": {
        "markers": (
            "embezzle",
            "embezzled",
            "entrusted",
            "company funds",
            "accountant",
            "employee funds",
            "personal expenses",
            "misappropriated funds",
            "breach of trust",
        ),
        "queries": (
            "Section 405 criminal breach of trust",
            "Section 408 criminal breach of trust by clerk or servant",
            "Section 409 criminal breach of trust by public servant banker merchant or agent",
        ),
        "preferred_sections": {"405", "408", "409"},
        "keywords": {
            "entrusted",
            "dominion",
            "dishonestly",
            "misappropriates",
            "converts",
            "clerk",
            "servant",
            "agent",
        },
    },
    "falsification": {
        "markers": (
            "false entry",
            "falsified",
            "altered records",
            "altered accounts",
            "destroyed accounts",
            "omitted entries",
            "books of account",
        ),
        "queries": (
            "Section 477-A falsification of accounts",
        ),
        "preferred_sections": {"477-A"},
        "keywords": {
            "falsification",
            "accounts",
            "false",
            "entry",
            "defraud",
        },
    },
    "unlawful_assembly": {
        "markers": (
            "mob",
            "riot",
            "rioting",
            "unlawful assembly",
            "common object",
            "stampede",
        ),
        "queries": (
            "Unlawful assembly and common object liability",
            "Rioting and use of force by unlawful assembly",
        ),
        "preferred_sections": set(),
        "keywords": {
            "assembly",
            "riot",
            "rioting",
            "common",
            "object",
            "force",
            "violence",
        },
    },
    "abetment": {
        "markers": (
            "incite",
            "inciting",
            "instigate",
            "instigating",
            "encourage",
            "abet",
            "abetment",
        ),
        "queries": (
            "Abetment by instigation or intentional aid",
            "Abetment of an offence by the public or by more than ten persons",
        ),
        "preferred_sections": {"107"},
        "keywords": {
            "abetment",
            "instigates",
            "conspiracy",
            "intentionally",
            "aids",
        },
    },
    "found_property": {
        "markers": (
            "found property",
            "found wallet",
            "lost wallet",
            "found on the road",
            "lost property",
            "later decided to keep",
            "kept it for personal use",
            "finder",
        ),
        "queries": (
            "Section 403 dishonest misappropriation of found property",
            "Section 378 theft property not in another person's possession",
        ),
        "preferred_sections": {"403", "378"},
        "keywords": {
            "found",
            "lost",
            "owner",
            "misappropriation",
            "possession",
            "dishonestly",
        },
    },
}


SPECIAL_SECTION_REQUIREMENTS: dict[str, set[str]] = {
    "317": {
        "heir",
        "inheritance",
        "succession",
        "beneficiary",
        "will",
        "estate",
    },
    "396": {
        "dacoity",
        "robbery",
        "five or more",
        "five persons",
        "gang",
    },
    "404": {
        "deceased",
        "death of owner",
        "estate",
        "servant of deceased",
    },
    "477-A": {
        "false entry",
        "falsified",
        "altered",
        "omitted",
        "accounts",
        "accounting records",
        "books",
    },
    "390": {
        "force",
        "fear",
        "threat",
        "hurt",
        "restraint",
        "weapon",
        "robbery",
    },
    "405": {
        "entrusted",
        "entrustment",
        "dominion",
        "agent",
        "employee",
        "servant",
        "clerk",
    },
}


STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "has",
    "he",
    "her",
    "his",
    "in",
    "is",
    "it",
    "of",
    "on",
    "or",
    "person",
    "that",
    "the",
    "their",
    "this",
    "to",
    "under",
    "was",
    "were",
    "which",
    "who",
    "with",
}
