# Generated by Django 6.0.7 on 2026-08-09 19:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='document_category_name_ci_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='document_category_code_ci_unique'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='document_category_name_not_blank'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='document_category_code_not_blank')],
            },
        ),
    ]
